name: CI
on: [push, pull_request]
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install -U pip
      - run: pip install -r requirements.txt
      - name: Import check for scripts
        run: |
          python - << 'PY'
          import os, importlib.util, sys
          folder = "scripts"
          failed = False
          for fn in os.listdir(folder):
              if fn.endswith(".py"):
                  path = os.path.join(folder, fn)
                  try:
                      spec = importlib.util.spec_from_file_location(fn[:-3], path)
                      mod = importlib.util.module_from_spec(spec)
                      # Only load the spec object; don't execute module code with heavy side effects.
                      # If you want to execute, uncomment next line:
                      # spec.loader.exec_module(mod)
                  except Exception as e:
                      failed = True
                      print(f"[WARN] Could not import spec for {fn}: {e}", file=sys.stderr)
          if failed:
              sys.exit(1)
          PY
